{
    "on": ["push"],
    "jobs": {
        "release": {
            "runs-on": "ubuntu-latest",
            "steps": [
                { "uses": "actions/checkout@v3" },
                { "run": "git submodule update --init --recursive" },
                { "run": "sudo apt-get install -y ninja-build" },
                { "run": "mkdir build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. && ninja" }
            ]
        }
    }
}
